version: "3"

services:
  ms-sql-server:
    build: ./mssql_database
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Geheim123"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolumeTestdb:/var/opt/mssql

volumes:
  sqlvolumeTestdb: